account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'
urlpatterns = [
    path('home/signup/', views.signup, name='signup'),
    path('home/login/', views.login, name='login'),
    path('home/logout/', views.logout, name='logout'),
    path('home/', views.home, name='home'),

    
    path('signup/custom/', views.signup_custom, name='signup_custom'),
    path('logout/custom/', views.logout_custom, name='logout_custom'),
    path('login/custom/', views.login_custom, name='login_custom'),


    path('login/test/', auth_views.LoginView.as_view(
            template_name='account/login_test.html'), name='login_test'),

]

community/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import FileDownloadView

app_name = 'community'

urlpatterns = [
    path('community_insert/', views.community_insert),
    path('community_list/', views.community_list.as_view()),  ## 여기 
    path('test/<int:post_id>/community_modify/', views.community_modify,name="community_modify"),
    path('test/<int:document_id>/', FileDownloadView.as_view(), name="download"),
    path('detail/<int:post_id>/community_modify/', views.community_modify,name="community_modify"),
    path('detail/<int:document_id>/', FileDownloadView.as_view(), name="download"),
    path('test/', views.test),
    path('test2/', views.test2),
    path('test/downloads/<int:id>/', views.downloads, name='downloads'),
    path('detail/', views.detail, name='detail'),
    path('detail/<int:post_id>/community_delete/', views.community_delete,name="community_delete"),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myref/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ref/', include('ref.urls')),
    path('community/', include('community.urls')),
    path('account/', include('account.urls')),
]+ static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

ref/urls.py
from django.urls import path
# from . import views
from .views import *
from ref import views as main_views

app_name = 'ref'

urlpatterns = [
    path('main/', main_v.as_view(), name='main'),
    path('main/mypage/', myPage.as_view(), name='mypage'),
    path('main/mypageINFO/', myPageEditInfo.as_view(), name='mypageINFO'),
    path('main/searchRecipe/', main_views.searchRecipeSSS.as_view(), name='searchRecipe'),
    path('main/searchRecipe2/', main_views.searchRecipeDetail.as_view(), name='searchRecipe2'),
    path('main/mypage/myboard/',myBoard.as_view(), name='myBoard'),
]

ref/models.py
from django.db import models
from django.forms import IntegerField
# account 
from account.models import Userinfo

# Create your models here.

# 레시피 테이블
class Recipe(models.Model):
    # 1. 레시피일련번호(RCP_SNO)
    rcp_sno = models.IntegerField(primary_key=True)
    ## 현재 나는 에러는 mysql id 문제
    # 2. **요리명(CKG_NM)**
    ckg_nm = models.TextField()
    # 3. 조회수(INQ_CNT)
    inq_cnt = models.IntegerField(null=True)
    # 4. 추천수 RCMM_CNT
    rcmm_cnt = models.IntegerField(null=True)
    # 5. 요리방법별명(CKG_MTH_ACTO_NM)
    ckg_mth_acto_nm = models.TextField()
    # 6. 요리상황별명(CKG_STA_ACTO_NM)
    ckg_sta_acto_nm = models.TextField()
    # 7. **요리재료별명(CKG_MTRL_ACTO_NM)**
    ckg_mtrl_acto_nm = models.TextField()
    # 8. 요리종류별명(CKG_KND_ACTO_NM)
    ckg_knd_acto_nm = models.TextField()
    # 9. 요리재료내용(CKG_MTRL_CN)
    ckg_mtrl_cn = models.TextField()
    # 10. 요리시간명(CKG_TIME_NM)
    ckg_time_nm = models.TextField()
    # 11. 재료 수(MTRL_CNT)
    mtrl_cnt = models.TextField()
    # 10. 재료(MTRL)
    mtrl = models.TextField()
    

# 유저 냉장고 테이블
class Mine(models.Model):
    # id
    seq = models.IntegerField(primary_key=True)
    # 유저 닉네임
    id = models.CharField(max_length=100)
    # 보유한 재료
    ingredients = models.CharField(max_length=50)
    # 유통기한
    expiry_date = models.DateField(null=True)    


# 요리 게시판 테이블
class Board(models.Model):
    # 보드 아이디
    board_id = models.IntegerField()
    # rcp_sno
    rcp_sno = models.ForeignKey(Recipe, on_delete=models.CASCADE, db_column='rcp_sno')
    # title
    board_title = models.CharField(max_length=50)
    # contents
    board_contents = models.TextField()

ref/views.py
from audioop import reverse
from distutils.command.check import check
from msilib.schema import ListView
from socket import AI_PASSIVE
from typing import Dict
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from myref import settings
from account.models import Userinfo
from .models import *
from django.views import View
from django.views.decorators.csrf import csrf_exempt
import requests
from isodate import parse_duration
from account.models import Userinfo
from itertools import *
from django.shortcuts import get_object_or_404
from community.models import Board

class main_v(View):
    array = []
    current_ingred = []       
    def get(self, request, *args, **kwargs):
        star = Recipe.objects.order_by('-inq_cnt')[0:10]
        recipe_list = Recipe.objects.all()
        userref_list = Mine.objects.all()
        return render(request,'ref/main.html',{'recipe_list':recipe_list,'userref_list':userref_list, 'star':star})
    
    def post(self, request, *args, **kwargs):
        try:
            username= request.session['username']    
        except KeyError as e:
            return render(request, 'ref/main.html')
        star = Recipe.objects.order_by('-inq_cnt')[0:10]
        mn = request.POST.get('material_name')
        if mn == '':
            return render(request, 'ref/main.html')
        ed = request.POST.get('expire_date')
        
        self.array =[]
        ingred = Mine.objects.filter(id=username)
        for i in range(len(ingred)):
            self.array.append(ingred[i].ingredients)
        temp = mn
        new_temp = Mine()
        if str(mn) not in self.array:
            self.array.append(mn)
            new_temp.ingredients = temp
            if ed != "":
                new_temp.expiry_date = ed
            new_temp.id = username
            new_temp.save()
        
        return render(request, 'ref/main.html', context={'array' : self.array, 'star':star})

class myPage(View):
    def get(self, request, *args, **kwargs):
        username= request.session['username']
        uinfo = Userinfo.objects.get(name=username)
        return render(request,'ref/mypage.html',{'uinfo':uinfo})
    
    def post(self, request, *args, **kwargs):
        uuu = Userinfo.objects.get(name=request.session["username"])
        return render(request,'ref/editMyinfo.html',{'uinfo':uuu})

class myPageEditInfo(View):
    def get(self, request, *args, **kwargs):
        username= request.session['username']
        uinfo = Userinfo.objects.get(name=username)
        return render(request,'ref/editMyinfo.html',{'uinfo':uinfo})
    
    def post(self, request, *args, **kwargs):
        uuu = Userinfo.objects.get(name=request.session["username"])
        uuu.password = request.POST.get("PW", uuu.password)
        uuu.last_name = request.POST.get("NICK")
        uuu.email = request.POST.get("email")
        return render(request,'ref/mypage.html',{'uinfo':uuu})

        
class searchRecipeDetail(View):
    def get(self,request, *args, **kwargs):
        array = request.session["recipe_list"]
        return render(request,'ref/recipedetail.html')
    
    
class searchRecipeSSS(View):
    def get(self,request, *args, **kwargs):
        from collections import defaultdict
        username= request.session['username']
        cntr=Recipe.objects.all().count()
        cntm=Mine.objects.filter(id=username).count()
        if cntm == 0:
            return render(request,'ref/main.html')

    # user의 재료 목록 가져와 일치하는 레시피 정렬
        dic = defaultdict(int)
        for i in range(0,cntm):
            filter_rcp= Recipe.objects.filter(ckg_mtrl_cn__contains=Mine.objects.filter(id=username)[i].ingredients).values('rcp_sno')
            filter_mtrl= Recipe.objects.filter(ckg_mtrl_cn__contains=Mine.objects.filter(id=username)[i].ingredients).values('mtrl_cnt')
            
            for j in range(len(filter_rcp)):
                if dic[filter_rcp[j]['rcp_sno']]:
                    dic[filter_rcp[j]['rcp_sno']] +=1
                else:
                    dic[filter_rcp[j]['rcp_sno']] = 1
                                
        arr1 =[]
        for i,v in dic.items():
            get_mtrl_cnt= Recipe.objects.get(rcp_sno=i)
            arr1.append((i,v,get_mtrl_cnt.mtrl_cnt))
            
        import operator
        result = sorted(arr1, key= lambda x : (-x[1], x[2]))

        arrays,keys_list = [],[]
        for i in range(12):
            query = Recipe.objects.get(rcp_sno=result[i][0])   
            keys_list.append(query.rcp_sno)
            arrays.append(query)
        request.session["recipe_list"] = keys_list
        return render(request,'ref/recipe.html',{'recipe_list':arrays})

    # 보이는 화면에서 처리할때 결과 나오는것.
    def post(self,request, *args, **kwargs):
        rcp_sno1 = request.POST.get("rcp_sno",0)
        query = Recipe.objects.get(rcp_sno=rcp_sno1)
        return render(request,'ref/recipedetail.html', {"query": query})

class myBoard(View):
    def get(self, request, *args, **kwargs):
        board=Board.objects.all()
        return render(request,'ref/myboard.html',{'board':board})

ref/templates/ref/editMyinfo.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
    .myprofile{
        font-family: "SUIT-Medium";
        position: relative;
        font-size: 20px;
    }
</style>

<br>
<div class = "myprofile">
    <div class="card mb-3" style="width : 50rem ;margin: auto; text-align : center;">
    <div class="row g-0">
        <div class="col-md-4"style ="text-align : center; border: 15px solid #36CCA6; object-fit: none";>
            <div style="margin-top : 0rem"><br></div>    
                <img src="{% static 'image/profile.jpg' %}" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
        <div class="card-body" style ="margin : 2rem; width : 40rem">
            <form action ="/ref/main/mypageINFO/" method="POST">
                {% csrf_token%}
                <div>
                    <h3 class="card-title" style="display:inline-block;">아이디2</h3>
                    <h3 style="display:inline-block; margin-left : 1.5rem; margin-right : 10rem" >
                        <input type = "text" style ="color : #36CCA6;display:inline-block;width:13rem;" value = {{user.username}} name = "ID" disabled>
                    </h3>
                </div>
                <div>
                    <h3 class="card-title" style="display:inline-block;">비밀번호</h3>
                    <h3 style="display:inline-block; margin-left : 1.5rem; margin-right : 10rem" >
                        <input type = "text" style ="color : #36CCA6;display:inline-block;width:13rem;"  name = "PW">
                    </h3>
                </div>
                <div>
                    <h3 class="card-title" style="display:inline-block;">닉네임</h3>
                    <h3 style="display:inline-block; margin-left : 1.5rem; margin-right : 10rem" >
                        <input type = "text" style ="color : #36CCA6;display:inline-block;width:13rem;" value = {{uinfo.last_name}} name = "NICK">
                    </h3>
                </div>
                <div>
                    <h3 class="card-title" style="display:inline-block;">이메일</h3>
                    <h3 style="display:inline-block; margin-left : 1.5rem; margin-right : 10rem" >
                        <input type = "text" style ="color : #36CCA6;display:inline-block;width:20rem;" value = {{uinfo.email}} name = "email">
                    </h3>
                </div>
                <div style="margin-bottom:0rem;"><br></div>
                <div>
                    <input style="text-align:center;position:absolute;width:10rem;" method = "POST" type="submit" name="editfinish" value="수정완료">
                </div>
            </form>
        </div>
        </div>
    </div>
    </div>
</div>
<br>

<hr>
<div style="margin:2rem 0rem; text-align:center;"></div>

<h2 style="font-family:SUIT-Medium ; font-size : 33px; margin : 0 10rem;"> 
    ❤ 내가 찜한 레시피
</h2>

{% include 'slider.html' %}


<hr>
<div style="margin:2rem 0rem; text-align:center;"></div>

<h2 style="font-family:SUIT-Medium ; font-size : 33px; margin : 0 10rem;"> 
    ❤ 내 게시물
</h2>

{% include 'slider.html' %}


{% endblock %}

ref/templates/ref/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
    .testing{
        font-family: "SUIT-Medium";
        position: relative;
        font-size: 20px;
    }
    .subtitle{
        font-family: "SUIT-Medium";
        position: relative;
        font-size: 23px; 
    }
    input {
        font-family: "SUIT-Medium";
        font-size: 15px;
        border: 0;
        border-radius: 15px;
        outline: none;
        padding-left: 10px;
        background-color: rgb(233, 233, 233);
        }
    .btn{
        font-family: "SUIT-Medium";
        display: inline-block;
        outline: none;
        cursor: pointer;
        font-weight: 600;
        border-radius: 3px;
        padding: 12px 24px;
        border: 0;
        color: #000021;
        background: #36CCA6;;
        line-height: 1.15;
        font-size: 16px;
    }
    .btn:hover {
        transition: all .1s ease;
        box-shadow: 0 0 0 0 #fff, 0 0 0 3px #36CCA6;;
    }
    .test{
        display: inline-block;

    }
    .test2{
        height: 2rem; 
        background-color: white; 
        border-radius : 2rem;
        padding : 0 10px 0 10px;
    }

</style>
<br>
<!-- 재료 이름, 유통기한 -->
<div style="text-align: center;">
    <span class = "testing" style="left: -12rem;">재료 이름</span>
    <span class = "testing" style="left: -1.5rem;">유통 기한(선택)</span>
    <br>
    <form action="/ref/main/", method = "post">
        {% csrf_token %}
        <input class = "testing" style= "width: 15rem; height: 2.5rem;" type="text" name ="material_name"/>
        <input class = "testing" style="width: 15rem; height: 2.5rem;" type="date" name="expire_date"/>
        <input type="submit" class="btn" style= "width: 5rem; height: 2.5rem; margin-left : 2rem; margin-top:-0.6rem; font-size: 18px;" value="입력">
    </form>
    <br>
</div>

<div style="text-align: center;">
    <!--  현재 재료 목록 -->
    <div style="text-align: center; margin-top : 1rem">
        <span class = "subtitle">🍽현재 재료 목록🍽</span>
        <div style="height: 15rem; background-color: #36CCA6; border-radius : 2rem; margin: auto; width : 45rem;">
            <div style="height : 15rem; padding : 2rem">
            {% if array %}
                {% for gg in array%}
                <li class="test">
                    <div class= "test2">
                        <a class="testing">{{gg}}</a>
                    </div>
                </li>
                {% endfor %}
            {% endif %}
            </div>
        </div>
        <div style="margin: 2rem;">
            {% if not user.is_authenticated%} 
            <a href="{% url 'account:login' %}?next={{request.path}}"style = "margin : auto 3rem;">
                <button type="button" class="btn">레시피 검색</button>
            </a>
            {% else %}
            <a href= "/ref/main/searchRecipe" style="margin : auto 3rem;">
                <button type="button" class="btn">레시피 검색</button>
            </a> 
            {% endif %}

        </div>
    </div>
</div>
<hr>

<div style="text-align: center; margin-top : 2rem">
    <span class = "subtitle">🔥인기 레시피🔥</span>

</div>

{% include 'slider.html' %}

{% endblock %}

ref/templates/ref/myboard.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12" style="margin-top:20px;">
            {% for item in board %}
                {% if user.last_name == item.write_id %}
                <a href="{% url 'community:detail' %}?id={{ item.id }}" class="card-link">
                    <h3>{{ item.regdate }} / {{ item.contents }}</h3>
                </a>
                    {% comment %} <a href={% url %} {% endcomment %}
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

ref/templates/ref/mypage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
    .myprofile{
        font-family: "SUIT-Medium";
        position: relative;
        font-size: 20px;
    }
    .headerbtn{
        font-size : 20px; 
        display: inline-block; 
        width: auto;
        color : #4e5052;
        font-family: "GongGothicMedium";
        }
    .headerbtn a {
        display: inline-block;
    }
    .headerbtn a:link {
        text-decoration: none;
        color: #3f464d;
    }
    .headerbtn a:visited {
        text-decoration: none;
        color: #3f464d;
    }
    .headerbtn a:active {
        text-decoration: none;
        color: #3f464d;
    }
    .headerbtn a:hover {
        text-decoration: none;
        color: #36CCA6;
        cursor: pointer;
    } 

</style>

<br>
<div class = "myprofile">
    <div class="card mb-3" style="width : 50rem ;margin: auto; text-align : center;">
    <div class="row g-0">
        <div class="col-md-4"style ="text-align : center; border: 15px solid #36CCA6; object-fit: none";>
            <div style="margin-top : 0rem"><br></div>    
                <img src="{% static 'image/profile.jpg' %}" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
        <div class="card-body" style ="margin : 2rem; width : 40rem">
            <div>
                <h3 class="card-title" style="display:inline-block;">아이디</h3>
                <h3 style="display:inline-block; margin-left : 1.5rem; margin-right : 10rem" >
                    <span style ="color : #36CCA6">{{user.username}}</span>
                </h3>
            </div>
            <div>
                <h3 class="card-title" style="display:inline-block;">닉네임</h3>
                <h3 style="display:inline-block; margin-left : 1.5rem; margin-right : 10rem" >
                    <span style ="color : #36CCA6">{{uinfo.last_name}}</span>
                </h3>
            </div>
            <div>
                <h3 class="card-title" style="display:inline-block;">이메일</h3>
                <h3 style="display:inline-block; margin-left : 1.5rem; margin-right : 10rem" >
                    <span style ="color : #36CCA6">{{uinfo.email}}</span>
                </h3>
            </div>
            <div style="margin-bottom:0rem;"><br></div>
            <div>
                <form action ="/ref/main/mypage/" method="POST">
                    {% csrf_token %}
                    <input style="text-align:center;position:absolute;width:10rem;" method="POST" type="submit" name="edit" value="수정">
                </form>
            </div>
        </div>
        </div>
    </div>
    </div>
</div>
<br>

<hr>
<div style="margin:2rem 0rem; text-align:center;"></div>

<div class = "headerbtn" style="margin : auto; text-align :center; width : 100%"> 
    <a style="font-size: 20px;" href="{% url 'ref:myBoard' %}">❤ 내 게시물 ❤</a>
</div>


{% endblock %}

ref/templates/ref/recipe.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    .cards-box {
        display: flex;
        justify-content: space-between;
        margin: 0 70px;
        margin-top: 65px;
        flex-wrap: wrap;
        {#float: left;#}
    }
    .btn{
        font-family: "SUIT-Medium";
        display: inline-block;
        outline: none;
        cursor: pointer;
        font-weight: 600;
        border-radius: 3px;
        padding: 12px 24px;
        border: 0;
        color: #000021;
        background: #36CCA6;;
        line-height: 1.15;
        font-size: 16px;
    }
    .btn:hover {
        transition: all .1s ease;
        box-shadow: 0 0 0 0 #fff, 0 0 0 3px #36CCA6;;
    }
</style>

{% csrf_token %}
<div class="card-colums" id="all_posting">
    <div id="card-box" class="cards-box">
        {% for item in recipe_list%}
            <div class="card" style="width: 17rem; margin-bottom:15px; margin-left: 10px;">
                <img class="card-img-top" src="/static/image/rep_img/{{item.rcp_sno}}.jpg/" alt="Card image cap"
                style="border-bottom: 1px solid #eee; height: 200px;">
                <div class="card-body">
                    <ul class='card-body-ul' style="margin-bottom : 3rem">
                        <p style="font-family : SUIT-Medium"> 이름 : {{ item.ckg_nm }}</p>
                        <p style="font-family : SUIT-Medium"> 재료 : {{ item.mtrl }}</p>
                        <div class="btn-detail" style = "text-align:center; position: absolute; top: 20rem; left:5rem">
                            <form action = "/ref/main/searchRecipe/" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name = "rcp_sno" value = {{item.rcp_sno}}>
                                <input  class="btn" value = "자세히" method = "POST" type="submit" name = "detailViews" style="margin-left: 100px; margin-bottom: 13px; height: 40px">
                                {% csrf_token %}
                            </form>
                        </div>
                    </ul>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

ref/templates/ref/recipedetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    .card-colums{
        margin: 0;
        font-family : "SUIT-Medium";
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        color: #212529;
        text-align: left;
    }
    .cards-box {
        display: flex;
        justify-content: space-between;
        margin: 0 70px;
        margin-top: 65px;
        flex-wrap: wrap;
        {#float: left;#}
    }
</style>

<div class="card" style="width: 17rem; margin : auto;">
    <img class="card-img-top" src="/static/image/rep_img/{{query.rcp_sno}}.jpg/" alt="Card image cap" style="border-bottom: 1px solid #eee; height: 200px;">
    <div class="card-body">
        <ul class='card-body-ul'>
            <p style="font-family : SUIT-Medium">이름 : {{ query.ckg_nm }}</p>
            <p style="font-family : SUIT-Medium"> 재료 : {{ query.mtrl }}</p>
            <div class="btn-detail">
                <p>
                    <a href="https://www.10000recipe.com/recipe/{{query.rcp_sno}}" style="font-family : SUIT-Medium">레시피 상세보기</a>
                </p>
            </div>
        </ul>
    </div>
</div>

{% endblock %}