community/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import FileDownloadView

app_name = 'community'

urlpatterns = [
    path('community_insert/', views.community_insert),
    path('community_list/', views.community_list.as_view()),  ## 여기 
    path('test/<int:post_id>/community_modify/', views.community_modify,name="community_modify"),
    path('test/<int:document_id>/', FileDownloadView.as_view(), name="download"),
    path('detail/<int:post_id>/community_modify/', views.community_modify,name="community_modify"),
    path('detail/<int:document_id>/', FileDownloadView.as_view(), name="download"),
    path('test/', views.test),
    path('test2/', views.test2),
    path('test/downloads/<int:id>/', views.downloads, name='downloads'),
    path('detail/', views.detail, name='detail'),
    path('detail/<int:post_id>/community_delete/', views.community_delete,name="community_delete"),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myref/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ref/', include('ref.urls')),
    path('community/', include('community.urls')),
    path('account/', include('account.urls')),
]+ static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

ref/urls.py
from django.urls import path
# from . import views
from .views import *
from ref import views as main_views

app_name = 'ref'

urlpatterns = [
    path('main/', main_v.as_view(), name='main'),
    path('main/mypage/', myPage.as_view(), name='mypage'),
    path('main/mypageINFO/', myPageEditInfo.as_view(), name='mypageINFO'),
    path('main/searchRecipe/', main_views.searchRecipeSSS.as_view(), name='searchRecipe'),
    path('main/searchRecipe2/', main_views.searchRecipeDetail.as_view(), name='searchRecipe2'),
    path('main/mypage/myboard/',myBoard.as_view(), name='myBoard'),
]

community/models.py
from importlib.resources import contents
from operator import mod
from django.db import models
from django.db.models.fields import CharField, IntegerField, FloatField, DateField
import datetime
from django.utils import timezone

class Board(models.Model):
    #커뮤니티 게시판의 게시글 번호
    id = models.IntegerField(primary_key=True)

    #요리 만드는 법 내용
    contents = models.TextField()

    #게시글 조회수
    views = models.IntegerField(default = 0)
    
    #게시글 날짜
    regdate = models.DateField(auto_now=True)

    #게시글 좋아요 수
    like = models.IntegerField(default = 0)

    #게시글 작성자 이름
    write_id = models.CharField(max_length=45)

    #파일 저장
    file =models.ImageField(upload_to='images', null=True)
    class Meta:
        managed = False
        db_table = "community_board"
        app_label = 'community_board'


 # 댓글
class Comment(models.Model):
     #댓글 번호
     com_id=models.IntegerField(primary_key=True)

     #댓글 작성자
     author = models.CharField(max_length=45)
    
     #댓글 내용
     contents = models.TextField()

     #작성날짜
     createdTime = models.DateField(auto_now=True)
    
     #게시글과의 외래키 
     id=models.ForeignKey(Board,on_delete=models.CASCADE,db_column='id')
     class Meta:
        managed = False
        db_table = "comment"
        app_label = 'comment'

community/views.py
from compileall import compile_dir
from distutils.command.upload import upload
from hmac import compare_digest
from importlib.resources import contents
from django.conf import settings
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Board
from .models import Comment
from contextlib import redirect_stderr
from django.shortcuts import render
from django.http import HttpResponse, request
from django.views import View
from .models import Board,Comment
from django.utils import timezone
from django.shortcuts import redirect
from django.views.generic import TemplateView
import datetime
from django.views.generic.detail import SingleObjectMixin
from django.http import FileResponse
from django.core.files.storage import FileSystemStorage
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
#
import urllib
import os
from django.http import HttpResponse, Http404
import mimetypes

#커뮤니티 글 쓰기
def community_insert(request):
    if request.method == 'POST':
         file=request.FILES['file']
         title = request.POST.get('title')
         write_id = request.POST.get('write_id')
         contents = request.POST.get('contents')
         m = Board()
         m.title=title
         m.write_id=write_id
         m.contents=contents
   
         m.views=0
         m.like=0
         m.file=file
         m.save()
    
         return redirect('/community/community_list')
    else:
        return render(request, 'community/community_insert.html',context={'text':'GET method!!!'})

class community_list(TemplateView):
     template_name = "community/community_list.html"
     def get(self, request):
          comment = Comment.objects.all()
          # comm.contents = contents
          community_list = Board.objects.all()
          print(community_list)
          list = {'comment':comment, 'board':community_list}
          return render(
               request, self.template_name, 
               {
                    'list':list
               }
          )

# 커뮤니티 글 수정
def community_modify(request,post_id):
     post=Board.objects.get(id=post_id)
     print(post)
     if request.method == 'POST':
          post.contents = request.POST['contents']
          try:
               post.file = request.FILES['file']
          except:
               post.file = None
          post.save()
          return redirect('/community/community_list')
     else:
          return render(request,'community/community_modify.html',{'post':post})

#커뮤니티 글 삭제
def delete(request, post_id):
     post = Board.objects.get(id=post_id)
     post.delete()
     return redirect('home')
def community_delete(request, post_id):
  post = Board.objects.get(id=post_id)
  post.delete()
  return redirect('/community/community_list')

#테스트창 완료 후 삭제
def test(request):
     return render(request, 'community/test.html')

def test2(request):
     return render(request, 'community/test2.html')

#테스트창 완료 후 삭제
def test(request):
     board_list=Board.objects.all()
     return render(request, 'community/test.html',{'board_list':board_list})

#파일 다운로드
class FileDownloadView(SingleObjectMixin, View):
    queryset = Board.objects.all()

    def get(self, request, document_id):
        object = self.get_object(id=document_id)

        file_path = object.attached.path
        file_type = object.content_type  # django file object에 content type 속성이 없어서 따로 저장한 필드
        fs = FileSystemStorage(file_path)
        response = FileResponse(fs.open(file_path, 'rb'), content_type=file_type)
        response['Content-Disposition'] = f'attachment; filename={object.file()}'
        
        return response


def downloads(request,id):
     #id = request.GET.get('id')
     print(id,22222222222)
     uploadFile = Board.objects.get(id=id)
     print(uploadFile,3333333333333)
     filepath = str(settings.BASE_DIR) + ('/media/%s' % uploadFile.file.name)
     filename = os.path.basename(filepath)
     with open(filepath, 'rb') as f:
          response = HttpResponse(f, content_type='application/octet-stream')
          response['Content-Disposition'] = 'attachment; filename=%s' % filename
          return response

def detail(request):
    if 'id' in request.GET:
        item = get_object_or_404(Board, pk=request.GET.get('id'))
        return render(request, 'community/detail.html', {'item': item})
    return HttpResponseRedirect('/community/community_list/')

community/templates/community/community__modify.html
{% load static %}
<head>
    <meta charset = "UTF-8">
    <title>Refrigerator</title>

    <!-- 부트스트랩 링크 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" 
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- 디폴트 CSS 링크 -->
    <link rel="stylesheet" type="text/css" href="{% static 'community.css' %}">

</head>
<div class="item">
    <a href="#" onclick="openzlog();" style="width:auto">글작성</a>
</div>

<div id="zlog" class="modal">
    <form class="modal-content" action="/community/community_insert/" method="post" enctype="multipart/form-data">
    <!-- <form class="modal-content" action="/community/community_insert/" method="post" > -->
        <span onclick="closezlog();" class="close">&times;</span>
        {% csrf_token %}
        <img src="{% static '/image/logo.png' %}" title="logo" class="com_logo" />
        <hr class="linebr2">
        <div style="text-align: center;"><span id="comm_mainfont">내 레시피 자랑</span><br><br><div>
        <div>
            
            <div style="float: left;" class="container">
                사진
                <input type="file" name="file" class="hidden_input" id="imageSelector"  accept="image/jpeg, image/jpg, image/png" multiple required/>
                <img class="thumb" required/>        
                 
            </div>
            <div class="comm_insert">
                <div style="float: center;"><textarea cols="50" rows="5" name="contents" class="text_input" placeholder="내용을 입력해주세요." required></textarea></div> 
            </div>
            <div style="float: right;">
                <input type="submit" value='등록' class="comm_insert" id="btn_insert">
            </div>
            <input type="hidden" name="write_id" value="id12345">
        </div>
    </form> 
</div>


<script type="text/javascript">


    var zlog = document.getElementById('zlog');
    function openzlog() {
        zlog.style.display = 'block';
    }
    function  closezlog(){
        zlog.style.display = 'none';
    }
    // 로그인 화면 바깥의 영역을 클릭할 경우 로그인 창 닫기
    window.onclick = function (event) {
        if (event.target==zlog) {
            zlog.style.display='none';
        }
    }
    
    document.addEventListener('DOMContentLoaded', function(){
        //이미지 객체 타입으로 이미지 확장자 밸리데이션
        var validateType = function(img){
            return (['image/jpeg','image/jpg','image/png'].indexOf(img.type) > -1);
        }
    
        var validateName = function(fname){
            let extensions = ['jpeg','jpg','png'];
            let fparts = fname.split('.');
            let fext = '';
        
            if(fparts.length > 1){
                fext = fparts[fparts.length-1];
            }
        
            let validated = false;
            
            if(fext != ''){
                extensions.forEach(function(ext){
                    if(ext == fext){
                        validated = true;
                    }
                });
            }
        
            return validated;
        }
    
        // 파일 선택 필드에 이벤트 리스너 등록
        document.getElementById('imageSelector').addEventListener('change', function(e){
            let elem = e.target;
            if(validateType(elem.files[0])){
                let preview = document.querySelector('.thumb');
                preview.src = URL.createObjectURL(elem.files[0]); //파일 객체에서 이미지 데이터 가져옴.
                document.querySelector('.dellink').style.display = 'block'; // 이미지 삭제 링크 표시
                preview.onload = function() {
                    URL.revokeObjectURL(preview.src); //URL 객체 해제
                }
            }else{
            console.log('이미지 파일이 아닙니다.');
            }
        });
    
    
    });
</script>

community/templates/community/community_insert.html
{% load static %}
<head>
    <meta charset = "UTF-8">
    <title>Refrigerator</title>

    <!-- 부트스트랩 링크 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" 
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- 디폴트 CSS 링크 -->
    <link rel="stylesheet" type="text/css" href="{% static 'community.css' %}">

</head>

    <form class="modal-content" action="/community/community_insert/" method="post" enctype="multipart/form-data">

        {% csrf_token %}
        <img src="{% static '/image/logo.png' %}" title="logo" class="com_logo" />
        <hr class="linebr2">
        <div style="text-align: center;"><span id="comm_mainfont">내 레시피 자랑</span><br><br><div>
        <div>
            
            <div style="float: center;" class="container">
                사진
                <input type="file" name="file" class="hidden_input" id="imageSelector"  accept="image/jpeg, image/jpg, image/png" multiple required/>
                <img class="thumb" required/>        
                 
            </div>
            <div class="comm_insert">
                <div style="float: center;"><textarea cols="50" rows="5" name="contents" class="text_input" placeholder="내용을 입력해주세요." required></textarea></div> 
            </div>
            <div style="float: right;">
                <input type="submit" value='등록' class="comm_insert" id="btn_insert">
            </div>
            <input type="hidden" name="write_id" value="{{ user.last_name }}">
        </div>
    </form> 

<script type="text/javascript">


    var zlog = document.getElementById('zlog');
    function openzlog() {
        zlog.style.display = 'block';
    }
    function  closezlog(){
        zlog.style.display = 'none';
    }
    // 로그인 화면 바깥의 영역을 클릭할 경우 로그인 창 닫기
    window.onclick = function (event) {
        if (event.target==zlog) {
            zlog.style.display='none';
        }
    }
    
    document.addEventListener('DOMContentLoaded', function(){
        //이미지 객체 타입으로 이미지 확장자 밸리데이션
        var validateType = function(img){
            return (['image/jpeg','image/jpg','image/png'].indexOf(img.type) > -1);
        }
    
        var validateName = function(fname){
            let extensions = ['jpeg','jpg','png'];
            let fparts = fname.split('.');
            let fext = '';
        
            if(fparts.length > 1){
                fext = fparts[fparts.length-1];
            }
        
            let validated = false;
            
            if(fext != ''){
                extensions.forEach(function(ext){
                    if(ext == fext){
                        validated = true;
                    }
                });
            }
        
            return validated;
        }
    
        // 파일 선택 필드에 이벤트 리스너 등록
        document.getElementById('imageSelector').addEventListener('change', function(e){
            let elem = e.target;
            if(validateType(elem.files[0])){
                let preview = document.querySelector('.thumb');
                preview.src = URL.createObjectURL(elem.files[0]); //파일 객체에서 이미지 데이터 가져옴.
                document.querySelector('.dellink').style.display = 'block'; // 이미지 삭제 링크 표시
                preview.onload = function() {
                    URL.revokeObjectURL(preview.src); //URL 객체 해제
                }
            }else{
            console.log('이미지 파일이 아닙니다.');
            }
        });
    
    
    });
</script>

community/templates/community/community_list.html
{% extends 'base2.html' %}

{% load static %}

{% block content %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

<style>

.openBtn {

margin-top: 2.5rem;

margin-left: 85%;

position: relative;

bottom: 20px;

right: 55px;

background-color: #36CCA6;

width: 80px;

height: 80px;

font-size: 60px;

color: white;

border: none;

border-radius: 75px;

text-align: center;

line-height: 75px;

}

.myrecipe {

font-family: "SUIT-Medium";

position: relative;

font-size: 25px;

text-align: center;

}

.container div {

width: 280px;

background-color: #FAFAFA;

display: relative;

justify-content: center;

align-items: center;

border-radius: 1rem;

flex-direction: column;

}

.container img {

width: 100%;

border-radius: 1rem;

}

.container:hover {

cursor: pointer;

}

.comment {

/*height: 80px;*/

border-radius: 0 0 1rem 1rem;

font-size: 15px;

text-align: left;

overflow: auto;

}

.comment span {

font-family: "SUIT-Medium";

font-size: 15px;

}

.comment_input {

height: 2.5rem;

width: 2.5rem;

border-radius: 10rem;

border: 1px solid black;

}

.add {

position: fixed;

bottom: 20px;

right: 55px;

background-color: #36CCA6;

width: 80px;

height: 80px;

font-size: 60px;

color: white;

border: none;

border-radius: 75px;

text-align: center;

line-height: 75px;

}

.add:hover {

color: gray;

cursor: pointer;

}

#chat_iframe {

margin-left: 0.32rem;

width: 41rem;

height: 51rem;

}

.modal {

display:none;

}

.modal-dialog {

position: relative;

width: 100%;

height: 90%;

/* 세로높이 */

overflow: auto;

/* 필요하면 스크롤 가능

background-color: rgba(0, 0, 0, 0);*/

background-color: lightgray;

max-width: 550px;

max-height : 100%

}

.detail-content {

margin: 0.5rem;

pointer-events: none;

}

.modal-content {

position: relative;

display: -ms-flexbox;

display: flex;

-ms-flex-direction: column;

flex-direction: column;

width: 500px;

height: 650px;

pointer-events: auto;

background-color: #fff;

background-clip: padding-box;

border: 1px solid rgba(0,0,0,.2);

border-radius: 0.3rem;

outline: 0;

}

.container div {

width: 300px;

background-color: antiquewhite;

}

.modal-header {

display: -ms-flexbox;

display: flex;

width:498px;

height:54px;

-ms-flex-align: start;

align-items: flex-start;

-ms-flex-pack: justify;

justify-content: space-between;

padding: 1rem;

border-bottom: 1px solid #e9ecef;

border-top-left-radius: 0.3rem;

border-top-right-radius: 0.3rem;

}

.modal-header img {

position: absolute;

width: 498px;

height: 650px;

top:0;

left:0;

height: 50%;

}

.modal-body {

position: absolute;

width:498px;

height:100px;

-ms-flex: 1 1 auto;

flex: 1 1 auto;

padding: 1rem;

background-color: lightgray;

padding: 16px;

}

.modal-footer {

display: flex;

width:498px;

height:124px;

flex-wrap: wrap;

flex-shrink: 0;

align-items: center;

justify-content: flex-end;

padding: 0.75rem;

border-top: 1px solid #dee2e6;

border-bottom-right-radius: calc(0.3rem - 1px);

border-bottom-left-radius: calc(0.3rem - 1px);

}
button.button_2 {
    position: relative;
    text-align: center;
    float:center;
    border: 0;
    outline: none;
    font-size: 20px;
    margin: 20px;;
    background:#36CCA6;
    color: white;
    padding: 5px;
    cursor: pointer;
    border-radius: 10px;
    font-family: "SUIT-Medium";
    margin-left:70%;
  }
  button.button_2:hover {
    color: white;
    background: orange;
    font-family: "SUIT-Medium";

  }

</style>

<div class="myrecipe">

<span style="size: 35px; color:#36CCA6; margin-bottom:20px;">내 요리를 자랑해보세요!</span>

</div>
{% if user.is_authenticated %}
<div  class="wrap">    
    <button  onclick="location.href='/community/community_insert/'" class="button_2">자랑글 등록</button>
</div>
{% endif %}
<div class="container">

{%for data in list.board%}

<a href="{% url 'community:detail' %}?id={{ data.id }}" class="card-link">

<div>

{% comment %} <img src=/media/{{data.file}} onerror='this.src="/static/image/profile.jpg"'> {% endcomment %}

<img src="{{ data.file.url }}">

<div class="comment">

</div>

</div>

</a>

{% endfor %}

</div>


<script>

var modal_detail = document.getElementById('detail-modal');

var imgs = document.querySelectorAll('.container img');

for (var i = 0; i < imgs.length; i++) {

imgs[i].addEventListener("click", open())

}

function open() {

modal_detail.style.display = 'block';

}

function close() {

modal_detail.style.display = 'none';

}

</script>

<script src="{% static 'js/magicgrid.js' %}"></script>

<script>

var imgs = document.querySelectorAll('.container div');

for(const con_img of imgs) {

con_img.addEventListener('click', console.log('clicked'));

}

</script>

{% comment %} <script>

function detail_open() {

document.getElementById('modal').style.display='block';

}

var imgs = document.querySelectorAll('.container img');

for (var i = 0; i < imgs.length; i++) {

imgs[i].addEventListener("click", detail_open())

}

</script> {% endcomment %}

<script src="{% static 'js/magicgrid.js' %}"></script>

{% endblock %}

community/templates/community/community_modify.html
{% load static %}
<head>
    <meta charset = "UTF-8">
    <title>Refrigerator</title>

    <!-- 부트스트랩 링크 -->
    {% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"  {% endcomment %}
    {% comment %} integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> {% endcomment %}

    <!-- 디폴트 CSS 링크 -->
    <link rel="stylesheet" type="text/css" href="{% static 'community.css' %}">

    <style>
    .insert_cook{
        border : 5px solid red;
    }
    </style>

</head>
{% comment %} <div class="item">
    <a href="#" onclick="openzlog();" style="width:auto">글 수정</a>
</div> {% endcomment %}

{% comment %} <div id="zlog" class="modal"> {% endcomment %}
    <form class="insert_cook" action="{% url 'community:community_modify' post.id %}" method="post" enctype="multipart/form-data">
        <span onclick="closezlog();" class="close">&times;</span>
        {% csrf_token %}
        <img src="{% static '/image/logo.png' %}" title="logo" class="com_logo" />
        <hr class="linebr2">
        <div style="text-align: center;"><span id="comm_mainfont">내 레시피 자랑</span><br><br><div>
        <div>
            
            <div style="float: left;" class="container">
                사진 
                <input type="file" name="file" class="hidden_input" id="imageSelector"  accept="image/jpeg, image/jpg, image/png" multiple required/>
                <img src="/media/{{post.file}}" class="thumb" required/>        
                 
            </div>
            <div class="comm_insert">
                <div style="float: center;"><textarea cols="50" rows="5" name="contents" class="text_input" placeholder="내용을 입력해주세요." value="" required></textarea></div> 
            </div>
            <div style="float: right;">
                <input type="submit" value='수정' class="comm_insert" id="btn_insert">
            </div>
            <input type="hidden" name="write_id" value="{{user.last_name}}">
        </div>
    </form> 


<script type="text/javascript">


    var zlog = document.getElementById('zlog');
    function openzlog() {
        zlog.style.display = 'block';
    }
    function  closezlog(){
        zlog.style.display = 'none';
    }
    // 로그인 화면 바깥의 영역을 클릭할 경우 로그인 창 닫기
    window.onclick = function (event) {
        if (event.target==zlog) {
            zlog.style.display='none';
        }
    }
    
    document.addEventListener('DOMContentLoaded', function(){
        //이미지 객체 타입으로 이미지 확장자 밸리데이션
        var validateType = function(img){
            return (['image/jpeg','image/jpg','image/png'].indexOf(img.type) > -1);
        }
    
        var validateName = function(fname){
            let extensions = ['jpeg','jpg','png'];
            let fparts = fname.split('.');
            let fext = '';
        
            if(fparts.length > 1){
                fext = fparts[fparts.length-1];
            }
        
            let validated = false;
            
            if(fext != ''){
                extensions.forEach(function(ext){
                    if(ext == fext){
                        validated = true;
                    }
                });
            }
        
            return validated;
        }
    
        // 파일 선택 필드에 이벤트 리스너 등록
        document.getElementById('imageSelector').addEventListener('change', function(e){
            let elem = e.target;
            if(validateType(elem.files[0])){
                let preview = document.querySelector('.thumb');
                preview.src = URL.createObjectURL(elem.files[0]); //파일 객체에서 이미지 데이터 가져옴.
                document.querySelector('.dellink').style.display = 'block'; // 이미지 삭제 링크 표시
                preview.onload = function() {
                    URL.revokeObjectURL(preview.src); //URL 객체 해제
                }
            }else{
            console.log('이미지 파일이 아닙니다.');
            }
        });
    
    
    });
</script>

community/templates/community/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12" style="margin-top:20px;">
            <h3>{{ item.contents }}</h3>
            <p>{{ item.regdate }}</p>
            {% if user.last_name == item.write_id %}
                 <a href="/community/detail/{{item.id}}/community_modify/">/수정</a>
                 <a href="/community/detail/{{item.id}}/community_delete/">/삭제</a>
            {% endif %}
            <form class="modal-content" action="/community/detail/downloads/{{item.id}}/" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div>
                  <input type="hidden" name="id" value="{{ item.id }}">
                    <div style="float: right;">
                        <input type="submit" value='다운' class="comm_insert" id="btn_insert">
                    </div>
                </div>
              </form> 
        </div>
    </div>
</div>
{% endblock %}

community/templates/community/test.html
<style>
  button {
      background-color: #F9B514;
      padding: 5px 10px;
      border-radius: 4px;
      cursor: pointer;
    }

    .modal {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      display: flex;
      justify-content: center;
      align-items: center;
    }

    .modal .bg {
      width: 100%;
      height: 100%;
      background-color: rgba(0, 0, 0, 0.6);
    }

    .modalBox {
      position: absolute;
      background-color: #fff;
      width: 80rem;
      height: 80rem;
      padding: 15px;
    }

    .modalBox button {
      display: block;
      width: 80px;
      margin: 0 auto;
    }

    .hidden {
      display: none;
    }
    #chat_iframe{
      width: 80rem;
      height: 80rem;
    }
</style>
{% for a in board_list %}
<div>
  <form action="" method="POST">
    {% csrf_token %}
    Username: <input type="/test/{{a.id}}/community_modify/" name="username" id="">

    <input type="submit" value="community_modify" id="">
</form>
  <input type="submit" value='등록' class="comm_insert" id="btn_insert">
  <a href="{% url 'community:community_modify' a.id %}">{{ user.username }}수정2222222222</a>
  <a href="/community/test/{{a.id}}/community_modify/">/수정</a>
  <a href="/community/test/{{a.id}}/community_delete/">/삭제</a>
  {% comment %} <img src="/media/{{a.file}}"> {% endcomment %}
</div>


<div>
  <label>첨부 파일</label>
  <div>{{ board_list.file }}</div>
  <form action='{% url "community:download" document_id=board_list.id %}'>
      <button type="submit">
      다운로드
      </button>
  </form>
</div>



{% endfor %}

<button class="openBtn">모달창 open</button>
<div class="modal hidden">
<div class="bg"></div>
<div class="modalBox">
  <iframe src="/community/community_insert" id="chat_iframe" >대체 내용</iframe>  
  <button class="closeBtn">✖</button>
</div>
</div>

<script>
const open = () => {
  document.querySelector(".modal").classList.remove("hidden");
}

const close = () => {
  document.querySelector(".modal").classList.add("hidden");
}

document.querySelector(".openBtn").addEventListener("click", open);
document.querySelector(".closeBtn").addEventListener("click", close);
document.querySelector(".bg").addEventListener("click", close);

</script>

community/templates/community/test2.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    .detail {
        width: 500px;
        height: 500px;
        border: 1px solid black;
    }
</style>    

<div class="detail">
    <div class="detail-img">

    </div>
    <div class="detail-content">

    </div>
    <div class="detail-comments">

    </div>
    <button class="edit">수정</button>
    <button class="delete">삭제</button>

</div>

{% endblock %}