account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'
urlpatterns = [
    path('home/signup/', views.signup, name='signup'),
    path('home/login/', views.login, name='login'),
    path('home/logout/', views.logout, name='logout'),
    path('home/', views.home, name='home'),

    
    path('signup/custom/', views.signup_custom, name='signup_custom'),
    path('logout/custom/', views.logout_custom, name='logout_custom'),
    path('login/custom/', views.login_custom, name='login_custom'),


    path('login/test/', auth_views.LoginView.as_view(
            template_name='account/login_test.html'), name='login_test'),

]

myref/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ref/', include('ref.urls')),
    path('community/', include('community.urls')),
    path('account/', include('account.urls')),
]+ static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

ref/urls.py
from django.urls import path
# from . import views
from .views import *
from ref import views as main_views

app_name = 'ref'

urlpatterns = [
    path('main/', main_v.as_view(), name='main'),
    path('main/mypage/', myPage.as_view(), name='mypage'),
    path('main/mypageINFO/', myPageEditInfo.as_view(), name='mypageINFO'),
    path('main/searchRecipe/', main_views.searchRecipeSSS.as_view(), name='searchRecipe'),
    path('main/searchRecipe2/', main_views.searchRecipeDetail.as_view(), name='searchRecipe2'),
    path('main/mypage/myboard/',myBoard.as_view(), name='myBoard'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body>
    {% include 'header.html' %}

    <hr>

    {% block content %}
    {% endblock %}
    {% comment %} {% incldue 'slider.html'%} {% endcomment %}

    {% include 'footer.html' %}

</body>


</html>

templates/base2.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body>
    {% include 'header.html' %}

    <hr>

    {% block content %}
    {% endblock %}
    {% comment %} {% incldue 'slider.html'%} {% endcomment %}

    {% include 'footer2.html' %}

</body>


</html>

templates/footer.html
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome//4.7.0/css/font-awesome.min.css">
    <!--Bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>
<style>
    body{
        background-color: #white; 
    }
    
    .our-team{
        padding: 30px 0 40px;
        background: white;
        text-align: center;
        overflow: hidden;
        position: relative;
    }

    .our-team .pic{
        display: inline-block;
        width: 130px;
        height: 130px;
        margin-bottom: 50px;
        position: relative;
        z-index: 1;    
    }
    
    .our-team .pic:before{
     content: "";
     width: 100%;
     background: #eb1768;
     position: absolute;
     bottom: 135%;
     right:0;
     left:0 ;
    transform: scale(3);
    transition: all 0.3s linear 0s;    
    }
    
    .our-team:hover .pic:before{
        height: 100% ;
    }
    
    .our-team .pic:after{
        content: "";
        width: 100%;
        height: 100%;
        border: radius 50%;
        position: absolute;
        top: 0;
        left: 0;
        z-index: -1;
    }
    
    .our-team .pic img{
        width: 100%;
        height: auto;
        border-radius: 50%;
        transform: scale(1);
        transition: all 0.9s ease 0s;
    
    }
    
    .our-team:hover .pic img{
        box-shadow: 0 0 0 14px #f7f5ec;
        transform: scale(0.7)
    }
    
    .our-team .team-content{
        margin-bottom: 30px;
    }
    
    .our-team .title{
        font-size: 22px;
        font-weight: 700;
        color: #4e5052;
        letter-spacing: 1px;
        text-transform: capitalize;
        margin-bottom: 5px;
    }
    
    .our-team .post{
        display: block;
        font-size: 15px;
        color: #4e5052;
        text-transform: capitalize;
    }
    
    .our-team .social{
        width: 100%;
        padding: 0;
        margin: 0;
        background: #eb1768;
        position: absolute;
        bottom: -100px;
        left: 0;
        transition: all 0.5s ease 0s; 
    }
    
    .our-team:hover .social{
        bottom: 0;
    }
    
    .our-team .social li{
        display: inline-block;
    }
    
    .our-team .social li a{
        display: block;
        padding: 10px;
        font-size: 17px;
        color:white;
        transition: all 0.5s ease 0s;
    }
    
    
    .our-team .social li a:hover{
        color: #eb1768;
        background: #f7f5ec;
        text-decoration: none;
    }
</style>

<div class="main_footer"; style="height: 38rem; font-family: 'SUIT-Medium'; background-color: #86918e;">
    <br>
    <div class="main_footer_btn">
        <br>
        <div style="text-align : center; font-size : 50px;">
            <b>CONTACT ME</b>
        </div>
        <div style="margin-top: 1rem;">
            <p>끼룩끼룩씨의 냉장고</p>
        </div>
        <div>
            <p>copyright 2022. 끼룩끼룩 All rights reserved</p>
        </div>
        <br>
    <div class="container" style="max-width : 60rem">
        <div class="row">
            <div class="col-md-3 col-sm-6" style="float : none ; margin : 0 auto;">
                <div class="our-team">
                    <div class="pic">
                        <img src="/static/image/윤경미모티콘4.png" alt="">
                    </div>
                    <div class="team-contenT">
                        <h3 class="title">권윤경</h3>
                        <span class="post">1기 에이블러</span>
                    </div>
                    <ul class="social">
                        <li><a href="https://github.com/yoonkyeongkwon" class="fa fa-github"></a></li>
                        <li><span style="font-size : 10px">dbsrud5916@gmail.com</span></li>
                    </ul>
                </div>
            </div>


            <div class="col-md-3 col-sm-6" style="float : none ; margin : 0 auto;">
                <div class="our-team">
                    <div class="pic">
                        <img src="/static/image/상희미모티콘2.png" alt="">
                    </div>
                    <div class="team-contenT">
                        <h3 class="title">김상희</h3>
                        <span class="post">1기 에이블러</span>
                    </div>
                    <ul class="social">
                        <li><a href="https://github.com/corgiccori97" class="fa fa-github"></a></li>
                        <li><span style="font-size : 10px">tkdgmlgg7@gmail.com</span></li>
                    </ul>
                </div>
            </div>

            <div class="col-md-3 col-sm-6" style="float : none ; margin : 0 auto;">
                <div class="our-team">
                    <div class="pic">
                        <img src="/static/image/수현미모티콘2.png" alt="">
                    </div>
                    <div class="team-contenT">
                        <h3 class="title">오수현</h3>
                        <span class="post">1기 에이블러</span>
                    </div>
                    <ul class="social">
                        <li><a href="https://github.com/soohyun97" class="fa fa-github"></a></li>
                        <li><span style="font-size : 10px">i970107@kakao.com</span></li>
                    </ul>
                </div>
            </div>

            <div class="col-md-3 col-sm-6" style="float : none ; margin : 0 auto;">
                <div class="our-team">
                    <div class="pic">
                        <img src="/static/image/윤지미모티콘2.png" alt="">
                    </div>
                    <div class="team-contenT">
                        <h3 class="title">이윤지</h3>
                        <span class="post">1기 에이블러</span>
                    </div>
                    <ul class="social">
                        <li><a href="https://github.com/dbswl2324" class="fa fa-github"></a></li>
                        <li><span style="font-size : 10px">leej23243@gmail.com></span></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

templates/footer2.html
{% load static %}

<div class="main_footer"; style="height: 10rem; font-family: 'SUIT-Medium'; background-color: #86918e;">
    <br>
    <div class="main_footer_btn">
        <br>
        <div style="margin-top: 1rem;">
            <p>끼룩끼룩씨의 냉장고</p>
        </div>
        <div>
            <p>copyright 2022. 끼룩끼룩 All rights reserved</p>
        </div>
    <br>
    </div>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset = "UTF-8">
    <title>Refrigerator</title>

    <!-- 부트스트랩 링크 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" 
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- 디폴트 CSS 링크 -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Swiper -->
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>
    <script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>

    <!-- font -->
    <style>
        @font-face {
            font-family: 'Y_Spotlight';
            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts-20-12@1.0/Y_Spotlight.woff') format('woff');
            font-weight: normal;
            font-style: normal;
        }
        @font-face {
            font-family: 'YUniverse-B';
            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_yuniverse@1.0/YUniverse-B.woff2') format('woff2');
            font-weight: normal;
            font-style: normal;
        }
        @font-face {
            font-family: 'YUniverse-L';
            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_yuniverse@1.0/YUniverse-L.woff2') format('woff2');
            font-weight: normal;
            font-style: normal;
        }

        @font-face {
          font-family: 'SUIT-Medium';
          src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_suit@1.0/SUIT-Medium.woff2') format('woff2');
          font-weight: normal;
          font-style: normal;
        }
        
        @font-face {
          font-family: 'GongGothicMedium';
          src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-10@1.0/GongGothicMedium.woff') format('woff');
          font-weight: normal;
          font-style: normal;
        }

    </style>


    <!-- 이미지 슬라이드 -->
    <link rel="stylesheet" type="text/css" href="http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <style>
      .slick-arrow{width: 45px;height: 45px; border: None; text-indent: -9999px; overflow: hidden; position : absolute; top:50%;
      transform: translateY(-50%);}
      .slick-prev{z-index: 100; left: 0%;
        background: url(https://blog.kakaocdn.net/dn/er4OgA/btrruohEMSP/5mcV2A2oHZ05XdhMxoIgM1/img.png) no-repeat 0 0;}
      .slick-next{right: -2%;
        background: url(https://blog.kakaocdn.net/dn/CUoFu/btrrAdl9SnC/l8uBlXu6HBV0JMaK3nr2q1/img.png) no-repeat 0 0;}
      .slider img{
        width: 100%;
        height: 100%;
      }
      .myslide .items{
        width : 200px;
        height : 250px;
        margin : 50px
      }
  
      .myslide .items img{
        width : 350px;
        height : 220px;
      }
  
      .slick-slider .slick-list .slick-track{
        position: relative;
        width : 100rem
      }
    </style>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script type="text/javascript" src="http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <script>
      $(function(){
        $('.myslide').slick({
          infinite: true,
          slidesToShow: 3,
          slidesToScroll: 3
        });
      })
    </script>

    <link rel="stylesheet" type="text/css" href="{% static 'community.css' %}">
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

  
</head>

templates/header.html
{% load static%}
<style>
    .headerbtn{
        font-size : 20px; 
        display: inline-block; 
        width: auto;
        color : #4e5052;
        font-family: "GongGothicMedium";
        }
    .headerbtn a {
        display: inline-block;
    }
    .headerbtn a:link {
        text-decoration: none;
        color: #3f464d;
    }
    .headerbtn a:visited {
        text-decoration: none;
        color: #3f464d;
    }
    .headerbtn a:active {
        text-decoration: none;
        color: #3f464d;
    }
    .headerbtn a:hover {
        text-decoration: none;
        color: #36CCA6;
        cursor: pointer;
    }    
</style>


<div class="main_header">
    <div>
        <a href="/ref/main">
            <img src="{% static '/image/logo.png' %}" title="메인 로고" style="width:200px; margin: 0rem 2rem;"/>
        </a>    
        <br>
    </div>
    <div>
        {% if not user.is_authenticated%}
        <div class="headerbtn" style = "margin : 1rem; visibility: hidden;">로그인</div>
        <div class="headerbtn" style = "margin : 1rem; visibility: hidden;">회원가입</div>
        <div class="headerbtn" style = "font-size : 2rem; width: 50rem;">끼룩끼룩씨의 냉장고</div>
        <div class = "headerbtn" style = "margin : 1rem;" >
            <a href="{% url 'account:login' %}?next={{request.path}}">로그인</a>
        </div>
        <div class = "headerbtn" style = "margin : 1rem;" >
            <a href="{% url 'account:signup' %}?next={{request.path}}">회원가입</a>
        </div>
        {% else %}
        <div class="headerbtn" style = "margin : 1rem; visibility: hidden;">로그아웃</div>
        <div class="headerbtn" style = "margin : 1rem; font-size : 15px; visibility: hidden;">안녕하세요 <span style ="color : #36CCA6">{{user.username}}</span> 님</div>
        <div class="headerbtn" style = "font-size : 2rem; width: 40rem;">끼룩끼룩씨의 냉장고</div>
        <div class="headerbtn" style = "margin : 1rem; font-size : 15px;">안녕하세요 <span style ="color : #36CCA6">{{user.username}}</span> 님</div>
        <div class="headerbtn" style = "margin : 1rem;">
            <a href="{% url 'account:logout' %}?next={{request.path}}">로그아웃</a>
        </div>
        {% endif %}
    </div>
    </div>
    <hr>
    <div style="margin : auto; text-align : center">
        <div class = "headerbtn">
            <a href="/ref/main" style = "margin : auto 3rem;">재료</a> 

            {% if not user.is_authenticated%} 
            <a href="{% url 'account:login' %}?next={{request.path}}"style = "margin : auto 3rem;">레시피검색</a>
            {% else %}
            <a href= "/ref/main/searchRecipe" style="margin : auto 3rem;">레시피검색</a> 
            {% endif %}
            
            {% if not user.is_authenticated%} 
            <a href="{% url 'account:login' %}?next={{request.path}}"style = "margin : auto 3rem;">요리커뮤니티</a>
            {% else %}
            <a href="/community/community_list"  style="margin : auto 3rem;">요리커뮤니티</a> 
            {% endif %}
        
            {% if not user.is_authenticated%} 
            <a href="{% url 'account:login' %}?next={{request.path}}" style = "margin : auto 3rem;">마이페이지</a>
            {% else %}
            <a href="/ref/main/mypage" style = "margin : auto 3rem;">마이페이지</a>
            {% endif %}

        </div>
    </div>
</div>

templates/slider.html
{% load static %} 
<style>
    .cook_name{
        text-align : center;
        margin-top : 1rem;
        font-size: 20px;
        font-family: "SUIT-Medium";
    }
   
</style>

<body>
    <div class="myslide" style="width: 80rem; margin :auto">
    {% for item in star%}
    <div class="items" style="text-align : center;">
        {% comment %} <a class = "cook_name" href = '#' style="text-decoration-line : none;">
            <img src="/static/image/rep_img/{{item.rcp_sno}}.jpg/" alt="" style="border-radius : 2rem">
        </a> {% endcomment %}

        <form class = "cook_name" action = "/ref/main/searchRecipe/" method="POST" style="text-decoration-line : none;">
            {% csrf_token %}
            <input type="hidden" name = "rcp_sno" value = {{item.rcp_sno}}>
            <input src="/static/image/rep_img/{{item.rcp_sno}}.jpg/" alt="" style="border-radius : 2rem; width : 350px; height : 220px;" method = "POST" type="image" name = "detailViews">
            {% csrf_token %}
        </form>

        <div class = "cook_name" href = '#' style="text-decoration-line : none;">
            {{item.ckg_nm}}
        </div>
    </div>
    {% endfor%}
    </div>
</body>